#!/usr/bin/env python3
"""Generate the embedded blue-noise threshold tiles for the Pages app.

The browser port can't run the FFT void-and-cluster generator at runtime, so we
precompute the 16/32/64/128 tiles here (reusing the *exact* Python generator) and
embed them in ``src/blue-noise-tiles.ts``.

Seed policy: tiles are generated at a FIXED seed (42) — the same seed the studio
sends for every render — so the browser blue-noise path is deterministic and
matches what the Python server would emit. Consequently the TS ``blue_noise``
method does not honour a runtime seed (one tile per size).

Tiles are stored as little-endian uint16 *ranks* (0..n*n-1), base64-encoded, to
keep the bundle small. The TS side reconstructs ``threshold = (rank+0.5)/(n*n)``.

Run:  python scripts/gen_blue_noise.py   (from colorworks/pages/)
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

import numpy as np

# Make the colorworks package importable (repo root is four levels up).
REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from colorworks.algorithms.dither import blue_noise_threshold_map  # noqa: E402

SEED = 42
SIZES = (16, 32, 64, 128)
OUT = Path(__file__).resolve().parents[1] / "src" / "blue-noise-tiles.ts"


def tile_ranks(size: int) -> np.ndarray:
    """Return the size*size integer rank grid for a tile at the fixed seed."""
    tile = blue_noise_threshold_map(size, size, size=size, seed=SEED)
    # threshold = (rank + 0.5) / (size*size)  ->  rank = threshold*n^2 - 0.5
    ranks = np.round(tile * (size * size) - 0.5).astype(np.uint16)
    assert ranks.min() == 0 and ranks.max() == size * size - 1, "ranks must be a permutation"
    return ranks.reshape(size, size)


def main() -> None:
    entries: list[str] = []
    for size in SIZES:
        ranks = tile_ranks(size)
        raw = ranks.astype("<u2").tobytes()  # little-endian uint16, row-major
        b64 = base64.b64encode(raw).decode("ascii")
        entries.append(f"  {size}: {b64!r},")

    body = "\n".join(entries)
    ts = (
        "// AUTO-GENERATED by scripts/gen_blue_noise.py — do not edit by hand.\n"
        "// Void-and-cluster blue-noise tiles, generated at fixed seed=42.\n"
        "// Each value is a little-endian uint16 rank grid (row-major), base64-encoded.\n"
        "// Reconstruct a threshold tile as: threshold = (rank + 0.5) / (size*size).\n"
        "export const BLUE_NOISE_TILES_B64: Record<number, string> = {\n"
        f"{body}\n"
        "};\n"
    )
    OUT.write_text(ts, encoding="utf-8")
    sizes = ", ".join(str(s) for s in SIZES)
    print(f"wrote {OUT.relative_to(Path.cwd())} — tiles for sizes {sizes} (seed={SEED})")


if __name__ == "__main__":
    main()
